/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) casadi_src_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_f10 CASADI_PREFIX(f10)
#define casadi_f11 CASADI_PREFIX(f11)
#define casadi_f12 CASADI_PREFIX(f12)
#define casadi_f13 CASADI_PREFIX(f13)
#define casadi_f14 CASADI_PREFIX(f14)
#define casadi_f15 CASADI_PREFIX(f15)
#define casadi_f16 CASADI_PREFIX(f16)
#define casadi_f17 CASADI_PREFIX(f17)
#define casadi_f18 CASADI_PREFIX(f18)
#define casadi_f19 CASADI_PREFIX(f19)
#define casadi_f2 CASADI_PREFIX(f2)
#define casadi_f20 CASADI_PREFIX(f20)
#define casadi_f21 CASADI_PREFIX(f21)
#define casadi_f22 CASADI_PREFIX(f22)
#define casadi_f23 CASADI_PREFIX(f23)
#define casadi_f24 CASADI_PREFIX(f24)
#define casadi_f25 CASADI_PREFIX(f25)
#define casadi_f3 CASADI_PREFIX(f3)
#define casadi_f4 CASADI_PREFIX(f4)
#define casadi_f5 CASADI_PREFIX(f5)
#define casadi_f6 CASADI_PREFIX(f6)
#define casadi_f7 CASADI_PREFIX(f7)
#define casadi_f8 CASADI_PREFIX(f8)
#define casadi_f9 CASADI_PREFIX(f9)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s1[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s2[4] = {0, 1, 0, 0};
static const casadi_int casadi_s3[23] = {4, 4, 0, 4, 8, 12, 16, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3};
static const casadi_int casadi_s4[9] = {5, 1, 0, 5, 0, 1, 2, 3, 4};
static const casadi_int casadi_s5[3] = {0, 0, 0};
static const casadi_int casadi_s6[33] = {5, 5, 0, 5, 10, 15, 20, 25, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4};
static const casadi_int casadi_s7[27] = {5, 4, 0, 5, 10, 15, 20, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4};
static const casadi_int casadi_s8[7] = {0, 4, 0, 0, 0, 0, 0};

casadi_real casadi_sq(casadi_real x) { return x*x;}

/* f_fun:(states[4],controls,params[0])->(xdot[4]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a2, a3, a4, a5, a6, a7, a8, a9;
  a0=arg[0]? arg[0][1] : 0;
  if (res[0]!=0) res[0][0]=a0;
  a1=2.1205800000000000e-002;
  a2=arg[0]? arg[0][2] : 0;
  a3=cos(a2);
  a3=(a1*a3);
  a4=8.7317999999999996e-003;
  a5=sin(a2);
  a5=(a4*a5);
  a6=cos(a2);
  a5=(a5*a6);
  a6=casadi_sq(a0);
  a6=(a5*a6);
  a7=4.0789980000000003e-001;
  a8=sin(a2);
  a7=(a7*a8);
  a6=(a6+a7);
  a6=(a3*a6);
  a8=9.6046499999999993e-003;
  a9=arg[1]? arg[1][0] : 0;
  a10=sin(a2);
  a1=(a1*a10);
  a10=arg[0]? arg[0][3] : 0;
  a11=casadi_sq(a10);
  a11=(a1*a11);
  a11=(a9+a11);
  a12=1.7463599999999999e-002;
  a13=sin(a2);
  a12=(a12*a13);
  a13=cos(a2);
  a12=(a12*a13);
  a13=(a12*a0);
  a13=(a13*a10);
  a11=(a11-a13);
  a11=(a8*a11);
  a6=(a6-a11);
  a11=casadi_sq(a3);
  a13=1.0351980000000000e-001;
  a2=sin(a2);
  a2=casadi_sq(a2);
  a4=(a4*a2);
  a13=(a13+a4);
  a4=(a8*a13);
  a11=(a11-a4);
  a6=(a6/a11);
  if (res[0]!=0) res[0][1]=a6;
  if (res[0]!=0) res[0][2]=a10;
  a6=casadi_sq(a10);
  a1=(a1*a6);
  a9=(a9+a1);
  a12=(a12*a0);
  a12=(a12*a10);
  a9=(a9-a12);
  a9=(a3*a9);
  a0=casadi_sq(a0);
  a5=(a5*a0);
  a5=(a5+a7);
  a5=(a13*a5);
  a9=(a9-a5);
  a3=casadi_sq(a3);
  a8=(a8*a13);
  a3=(a3-a8);
  a9=(a9/a3);
  if (res[0]!=0) res[0][3]=a9;
  return 0;
}

CASADI_SYMBOL_EXPORT int f_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int f_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int f_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void f_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int f_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void f_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void f_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void f_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int f_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int f_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real f_fun_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* f_fun_name_in(casadi_int i){
  switch (i) {
    case 0: return "states";
    case 1: return "controls";
    case 2: return "params";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* f_fun_name_out(casadi_int i){
  switch (i) {
    case 0: return "xdot";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* f_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* f_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int f_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* vdeFun:(i0[4],i1,i2[0],i3[4x4],i4[4])->(o0[4x4],o1[4]) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a3, a30, a31, a32, a33, a34, a35, a36, a37, a38, a39, a4, a40, a41, a42, a43, a44, a45, a46, a47, a48, a49, a5, a50, a51, a52, a53, a54, a55, a56, a57, a58, a59, a6, a7, a8, a9;
  a0=arg[3]? arg[3][1] : 0;
  if (res[0]!=0) res[0][0]=a0;
  a1=2.1205800000000000e-002;
  a2=arg[0]? arg[0][2] : 0;
  a3=cos(a2);
  a3=(a1*a3);
  a4=arg[0]? arg[0][1] : 0;
  a5=casadi_sq(a4);
  a6=cos(a2);
  a7=8.7317999999999996e-003;
  a8=cos(a2);
  a9=arg[3]? arg[3][2] : 0;
  a10=(a8*a9);
  a10=(a7*a10);
  a10=(a6*a10);
  a11=sin(a2);
  a11=(a7*a11);
  a12=sin(a2);
  a13=(a12*a9);
  a13=(a11*a13);
  a10=(a10-a13);
  a13=(a5*a10);
  a14=(a11*a6);
  a15=(a4+a4);
  a16=(a15*a0);
  a16=(a14*a16);
  a13=(a13+a16);
  a16=4.0789980000000003e-001;
  a17=cos(a2);
  a18=(a17*a9);
  a18=(a16*a18);
  a13=(a13+a18);
  a13=(a3*a13);
  a19=(a14*a5);
  a20=sin(a2);
  a20=(a16*a20);
  a19=(a19+a20);
  a21=sin(a2);
  a22=(a21*a9);
  a22=(a1*a22);
  a23=(a19*a22);
  a13=(a13-a23);
  a23=9.6046499999999993e-003;
  a24=arg[0]? arg[0][3] : 0;
  a25=casadi_sq(a24);
  a26=cos(a2);
  a27=(a26*a9);
  a27=(a1*a27);
  a28=(a25*a27);
  a29=sin(a2);
  a29=(a1*a29);
  a30=(a24+a24);
  a31=arg[3]? arg[3][3] : 0;
  a32=(a30*a31);
  a32=(a29*a32);
  a28=(a28+a32);
  a32=cos(a2);
  a33=1.7463599999999999e-002;
  a34=cos(a2);
  a35=(a34*a9);
  a35=(a33*a35);
  a35=(a32*a35);
  a36=sin(a2);
  a36=(a33*a36);
  a37=sin(a2);
  a38=(a37*a9);
  a38=(a36*a38);
  a35=(a35-a38);
  a38=(a4*a35);
  a39=(a36*a32);
  a40=(a39*a0);
  a38=(a38+a40);
  a38=(a24*a38);
  a40=(a39*a4);
  a41=(a40*a31);
  a38=(a38+a41);
  a28=(a28-a38);
  a28=(a23*a28);
  a13=(a13-a28);
  a28=casadi_sq(a3);
  a38=1.0351980000000000e-001;
  a41=sin(a2);
  a42=casadi_sq(a41);
  a42=(a7*a42);
  a38=(a38+a42);
  a42=(a23*a38);
  a28=(a28-a42);
  a13=(a13/a28);
  a42=(a3*a19);
  a43=arg[1]? arg[1][0] : 0;
  a44=(a29*a25);
  a44=(a43+a44);
  a45=(a40*a24);
  a44=(a44-a45);
  a44=(a23*a44);
  a42=(a42-a44);
  a42=(a42/a28);
  a44=(a42/a28);
  a45=(a3+a3);
  a46=(a45*a22);
  a47=(a41+a41);
  a48=cos(a2);
  a9=(a48*a9);
  a9=(a47*a9);
  a9=(a7*a9);
  a49=(a23*a9);
  a46=(a46+a49);
  a46=(a44*a46);
  a13=(a13+a46);
  if (res[0]!=0) res[0][1]=a13;
  if (res[0]!=0) res[0][2]=a31;
  a13=casadi_sq(a24);
  a27=(a13*a27);
  a46=(a24+a24);
  a49=(a46*a31);
  a49=(a29*a49);
  a27=(a27+a49);
  a35=(a4*a35);
  a49=(a39*a0);
  a35=(a35+a49);
  a35=(a24*a35);
  a49=(a39*a4);
  a31=(a49*a31);
  a35=(a35+a31);
  a27=(a27-a35);
  a27=(a3*a27);
  a35=(a29*a13);
  a43=(a43+a35);
  a35=(a49*a24);
  a43=(a43-a35);
  a35=(a43*a22);
  a27=(a27-a35);
  a35=casadi_sq(a4);
  a31=(a14*a35);
  a31=(a31+a20);
  a20=(a31*a9);
  a10=(a35*a10);
  a50=(a4+a4);
  a0=(a50*a0);
  a0=(a14*a0);
  a10=(a10+a0);
  a10=(a10+a18);
  a10=(a38*a10);
  a20=(a20+a10);
  a27=(a27-a20);
  a20=casadi_sq(a3);
  a10=(a23*a38);
  a20=(a20-a10);
  a27=(a27/a20);
  a10=(a3*a43);
  a18=(a38*a31);
  a10=(a10-a18);
  a10=(a10/a20);
  a18=(a10/a20);
  a0=(a3+a3);
  a22=(a0*a22);
  a9=(a23*a9);
  a22=(a22+a9);
  a22=(a18*a22);
  a27=(a27+a22);
  if (res[0]!=0) res[0][3]=a27;
  a27=arg[3]? arg[3][5] : 0;
  if (res[0]!=0) res[0][4]=a27;
  a22=arg[3]? arg[3][6] : 0;
  a9=(a8*a22);
  a9=(a7*a9);
  a9=(a6*a9);
  a51=(a12*a22);
  a51=(a11*a51);
  a9=(a9-a51);
  a51=(a5*a9);
  a52=(a15*a27);
  a52=(a14*a52);
  a51=(a51+a52);
  a52=(a17*a22);
  a52=(a16*a52);
  a51=(a51+a52);
  a51=(a3*a51);
  a53=(a21*a22);
  a53=(a1*a53);
  a54=(a19*a53);
  a51=(a51-a54);
  a54=(a26*a22);
  a54=(a1*a54);
  a55=(a25*a54);
  a56=arg[3]? arg[3][7] : 0;
  a57=(a30*a56);
  a57=(a29*a57);
  a55=(a55+a57);
  a57=(a34*a22);
  a57=(a33*a57);
  a57=(a32*a57);
  a58=(a37*a22);
  a58=(a36*a58);
  a57=(a57-a58);
  a58=(a4*a57);
  a59=(a39*a27);
  a58=(a58+a59);
  a58=(a24*a58);
  a59=(a40*a56);
  a58=(a58+a59);
  a55=(a55-a58);
  a55=(a23*a55);
  a51=(a51-a55);
  a51=(a51/a28);
  a55=(a45*a53);
  a22=(a48*a22);
  a22=(a47*a22);
  a22=(a7*a22);
  a58=(a23*a22);
  a55=(a55+a58);
  a55=(a44*a55);
  a51=(a51+a55);
  if (res[0]!=0) res[0][5]=a51;
  if (res[0]!=0) res[0][6]=a56;
  a54=(a13*a54);
  a51=(a46*a56);
  a51=(a29*a51);
  a54=(a54+a51);
  a57=(a4*a57);
  a51=(a39*a27);
  a57=(a57+a51);
  a57=(a24*a57);
  a56=(a49*a56);
  a57=(a57+a56);
  a54=(a54-a57);
  a54=(a3*a54);
  a57=(a43*a53);
  a54=(a54-a57);
  a57=(a31*a22);
  a9=(a35*a9);
  a27=(a50*a27);
  a27=(a14*a27);
  a9=(a9+a27);
  a9=(a9+a52);
  a9=(a38*a9);
  a57=(a57+a9);
  a54=(a54-a57);
  a54=(a54/a20);
  a53=(a0*a53);
  a22=(a23*a22);
  a53=(a53+a22);
  a53=(a18*a53);
  a54=(a54+a53);
  if (res[0]!=0) res[0][7]=a54;
  a54=arg[3]? arg[3][9] : 0;
  if (res[0]!=0) res[0][8]=a54;
  a53=arg[3]? arg[3][10] : 0;
  a22=(a8*a53);
  a22=(a7*a22);
  a22=(a6*a22);
  a57=(a12*a53);
  a57=(a11*a57);
  a22=(a22-a57);
  a57=(a5*a22);
  a9=(a15*a54);
  a9=(a14*a9);
  a57=(a57+a9);
  a9=(a17*a53);
  a9=(a16*a9);
  a57=(a57+a9);
  a57=(a3*a57);
  a52=(a21*a53);
  a52=(a1*a52);
  a27=(a19*a52);
  a57=(a57-a27);
  a27=(a26*a53);
  a27=(a1*a27);
  a56=(a25*a27);
  a51=arg[3]? arg[3][11] : 0;
  a55=(a30*a51);
  a55=(a29*a55);
  a56=(a56+a55);
  a55=(a34*a53);
  a55=(a33*a55);
  a55=(a32*a55);
  a58=(a37*a53);
  a58=(a36*a58);
  a55=(a55-a58);
  a58=(a4*a55);
  a59=(a39*a54);
  a58=(a58+a59);
  a58=(a24*a58);
  a59=(a40*a51);
  a58=(a58+a59);
  a56=(a56-a58);
  a56=(a23*a56);
  a57=(a57-a56);
  a57=(a57/a28);
  a56=(a45*a52);
  a53=(a48*a53);
  a53=(a47*a53);
  a53=(a7*a53);
  a58=(a23*a53);
  a56=(a56+a58);
  a56=(a44*a56);
  a57=(a57+a56);
  if (res[0]!=0) res[0][9]=a57;
  if (res[0]!=0) res[0][10]=a51;
  a27=(a13*a27);
  a57=(a46*a51);
  a57=(a29*a57);
  a27=(a27+a57);
  a55=(a4*a55);
  a57=(a39*a54);
  a55=(a55+a57);
  a55=(a24*a55);
  a51=(a49*a51);
  a55=(a55+a51);
  a27=(a27-a55);
  a27=(a3*a27);
  a55=(a43*a52);
  a27=(a27-a55);
  a55=(a31*a53);
  a22=(a35*a22);
  a54=(a50*a54);
  a54=(a14*a54);
  a22=(a22+a54);
  a22=(a22+a9);
  a22=(a38*a22);
  a55=(a55+a22);
  a27=(a27-a55);
  a27=(a27/a20);
  a52=(a0*a52);
  a53=(a23*a53);
  a52=(a52+a53);
  a52=(a18*a52);
  a27=(a27+a52);
  if (res[0]!=0) res[0][11]=a27;
  a27=arg[3]? arg[3][13] : 0;
  if (res[0]!=0) res[0][12]=a27;
  a52=arg[3]? arg[3][14] : 0;
  a8=(a8*a52);
  a8=(a7*a8);
  a8=(a6*a8);
  a12=(a12*a52);
  a12=(a11*a12);
  a8=(a8-a12);
  a12=(a5*a8);
  a15=(a15*a27);
  a15=(a14*a15);
  a12=(a12+a15);
  a17=(a17*a52);
  a17=(a16*a17);
  a12=(a12+a17);
  a12=(a3*a12);
  a21=(a21*a52);
  a21=(a1*a21);
  a15=(a19*a21);
  a12=(a12-a15);
  a26=(a26*a52);
  a26=(a1*a26);
  a15=(a25*a26);
  a53=arg[3]? arg[3][15] : 0;
  a30=(a30*a53);
  a30=(a29*a30);
  a15=(a15+a30);
  a34=(a34*a52);
  a34=(a33*a34);
  a34=(a32*a34);
  a37=(a37*a52);
  a37=(a36*a37);
  a34=(a34-a37);
  a37=(a4*a34);
  a30=(a39*a27);
  a37=(a37+a30);
  a37=(a24*a37);
  a30=(a40*a53);
  a37=(a37+a30);
  a15=(a15-a37);
  a15=(a23*a15);
  a12=(a12-a15);
  a12=(a12/a28);
  a45=(a45*a21);
  a48=(a48*a52);
  a47=(a47*a48);
  a47=(a7*a47);
  a48=(a23*a47);
  a45=(a45+a48);
  a44=(a44*a45);
  a12=(a12+a44);
  if (res[0]!=0) res[0][13]=a12;
  if (res[0]!=0) res[0][14]=a53;
  a26=(a13*a26);
  a46=(a46*a53);
  a46=(a29*a46);
  a26=(a26+a46);
  a34=(a4*a34);
  a46=(a39*a27);
  a34=(a34+a46);
  a34=(a24*a34);
  a53=(a49*a53);
  a34=(a34+a53);
  a26=(a26-a34);
  a26=(a3*a26);
  a34=(a43*a21);
  a26=(a26-a34);
  a34=(a31*a47);
  a8=(a35*a8);
  a50=(a50*a27);
  a50=(a14*a50);
  a8=(a8+a50);
  a8=(a8+a17);
  a8=(a38*a8);
  a34=(a34+a8);
  a26=(a26-a34);
  a26=(a26/a20);
  a0=(a0*a21);
  a47=(a23*a47);
  a0=(a0+a47);
  a18=(a18*a0);
  a26=(a26+a18);
  if (res[0]!=0) res[0][15]=a26;
  a26=arg[4]? arg[4][1] : 0;
  if (res[1]!=0) res[1][0]=a26;
  a18=-9.6046499999999993e-003;
  a18=(a18/a28);
  a0=cos(a2);
  a47=arg[4]? arg[4][2] : 0;
  a0=(a0*a47);
  a0=(a7*a0);
  a6=(a6*a0);
  a0=sin(a2);
  a0=(a0*a47);
  a11=(a11*a0);
  a6=(a6-a11);
  a5=(a5*a6);
  a11=(a4+a4);
  a11=(a11*a26);
  a11=(a14*a11);
  a5=(a5+a11);
  a11=cos(a2);
  a11=(a11*a47);
  a16=(a16*a11);
  a5=(a5+a16);
  a5=(a3*a5);
  a11=sin(a2);
  a11=(a11*a47);
  a11=(a1*a11);
  a19=(a19*a11);
  a5=(a5-a19);
  a19=cos(a2);
  a19=(a19*a47);
  a1=(a1*a19);
  a25=(a25*a1);
  a19=(a24+a24);
  a0=arg[4]? arg[4][3] : 0;
  a19=(a19*a0);
  a19=(a29*a19);
  a25=(a25+a19);
  a19=cos(a2);
  a19=(a19*a47);
  a33=(a33*a19);
  a32=(a32*a33);
  a33=sin(a2);
  a33=(a33*a47);
  a36=(a36*a33);
  a32=(a32-a36);
  a36=(a4*a32);
  a33=(a39*a26);
  a36=(a36+a33);
  a36=(a24*a36);
  a40=(a40*a0);
  a36=(a36+a40);
  a25=(a25-a36);
  a25=(a23*a25);
  a5=(a5-a25);
  a5=(a5/a28);
  a42=(a42/a28);
  a28=(a3+a3);
  a28=(a28*a11);
  a41=(a41+a41);
  a2=cos(a2);
  a2=(a2*a47);
  a41=(a41*a2);
  a7=(a7*a41);
  a41=(a23*a7);
  a28=(a28+a41);
  a42=(a42*a28);
  a5=(a5+a42);
  a18=(a18+a5);
  if (res[1]!=0) res[1][1]=a18;
  if (res[1]!=0) res[1][2]=a0;
  a18=(a3/a20);
  a13=(a13*a1);
  a1=(a24+a24);
  a1=(a1*a0);
  a29=(a29*a1);
  a13=(a13+a29);
  a32=(a4*a32);
  a39=(a39*a26);
  a32=(a32+a39);
  a24=(a24*a32);
  a49=(a49*a0);
  a24=(a24+a49);
  a13=(a13-a24);
  a13=(a3*a13);
  a43=(a43*a11);
  a13=(a13-a43);
  a31=(a31*a7);
  a35=(a35*a6);
  a4=(a4+a4);
  a4=(a4*a26);
  a14=(a14*a4);
  a35=(a35+a14);
  a35=(a35+a16);
  a38=(a38*a35);
  a31=(a31+a38);
  a13=(a13-a31);
  a13=(a13/a20);
  a10=(a10/a20);
  a3=(a3+a3);
  a3=(a3*a11);
  a23=(a23*a7);
  a3=(a3+a23);
  a10=(a10*a3);
  a13=(a13+a10);
  a18=(a18+a13);
  if (res[1]!=0) res[1][3]=a18;
  return 0;
}

CASADI_SYMBOL_EXPORT int vdeFun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f1(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int vdeFun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int vdeFun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void vdeFun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int vdeFun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void vdeFun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void vdeFun_incref(void) {
}

CASADI_SYMBOL_EXPORT void vdeFun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int vdeFun_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int vdeFun_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real vdeFun_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* vdeFun_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* vdeFun_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* vdeFun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    case 4: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* vdeFun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    case 1: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int vdeFun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* adj_ERK_fun:(i0[4],i1,i2[0],i3[4])->(o0[5]) */
static int casadi_f2(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a3, a30, a31, a32, a33, a34, a35, a36, a37, a38, a4, a5, a6, a7, a8, a9;
  a0=0.;
  if (res[0]!=0) res[0][0]=a0;
  a0=1.7463599999999999e-002;
  a1=arg[0]? arg[0][2] : 0;
  a2=sin(a1);
  a2=(a0*a2);
  a3=cos(a1);
  a4=(a2*a3);
  a5=arg[0]? arg[0][3] : 0;
  a6=9.6046499999999993e-003;
  a7=arg[3]? arg[3][1] : 0;
  a8=2.1205800000000000e-002;
  a9=cos(a1);
  a9=(a8*a9);
  a10=casadi_sq(a9);
  a11=1.0351980000000000e-001;
  a12=8.7317999999999996e-003;
  a13=sin(a1);
  a14=casadi_sq(a13);
  a14=(a12*a14);
  a11=(a11+a14);
  a14=(a6*a11);
  a10=(a10-a14);
  a14=(a7/a10);
  a15=(a6*a14);
  a16=(a5*a15);
  a17=(a4*a16);
  a18=arg[0]? arg[0][1] : 0;
  a19=(a18+a18);
  a20=sin(a1);
  a20=(a12*a20);
  a21=cos(a1);
  a22=(a20*a21);
  a23=arg[3]? arg[3][3] : 0;
  a24=casadi_sq(a9);
  a25=(a6*a11);
  a24=(a24-a25);
  a25=(a23/a24);
  a26=(a11*a25);
  a27=(a22*a26);
  a19=(a19*a27);
  a27=(a9*a25);
  a28=(a5*a27);
  a29=(a4*a28);
  a19=(a19+a29);
  a17=(a17-a19);
  a19=(a18+a18);
  a29=(a9*a14);
  a30=(a22*a29);
  a19=(a19*a30);
  a17=(a17+a19);
  a19=arg[3]? arg[3][0] : 0;
  a17=(a17+a19);
  if (res[0]!=0) res[0][1]=a17;
  a17=cos(a1);
  a13=(a13+a13);
  a19=arg[1]? arg[1][0] : 0;
  a30=sin(a1);
  a30=(a8*a30);
  a31=casadi_sq(a5);
  a32=(a30*a31);
  a32=(a19+a32);
  a33=(a4*a18);
  a34=(a33*a5);
  a32=(a32-a34);
  a34=(a9*a32);
  a35=casadi_sq(a18);
  a36=(a22*a35);
  a37=4.0789980000000003e-001;
  a38=sin(a1);
  a38=(a37*a38);
  a36=(a36+a38);
  a11=(a11*a36);
  a34=(a34-a11);
  a34=(a34/a24);
  a34=(a34/a24);
  a34=(a34*a23);
  a23=(a6*a34);
  a36=(a36*a25);
  a23=(a23-a36);
  a36=casadi_sq(a18);
  a22=(a22*a36);
  a22=(a22+a38);
  a38=(a9*a22);
  a24=casadi_sq(a5);
  a11=(a30*a24);
  a19=(a19+a11);
  a4=(a4*a18);
  a11=(a4*a5);
  a19=(a19-a11);
  a19=(a6*a19);
  a38=(a38-a19);
  a38=(a38/a10);
  a38=(a38/a10);
  a38=(a38*a7);
  a6=(a6*a38);
  a23=(a23+a6);
  a23=(a12*a23);
  a13=(a13*a23);
  a17=(a17*a13);
  a13=sin(a1);
  a16=(a18*a16);
  a18=(a18*a28);
  a16=(a16-a18);
  a2=(a2*a16);
  a13=(a13*a2);
  a17=(a17-a13);
  a13=cos(a1);
  a3=(a3*a16);
  a0=(a0*a3);
  a13=(a13*a0);
  a17=(a17+a13);
  a13=cos(a1);
  a31=(a31*a27);
  a24=(a24*a15);
  a31=(a31-a24);
  a31=(a8*a31);
  a13=(a13*a31);
  a17=(a17+a13);
  a13=cos(a1);
  a31=(a29-a26);
  a37=(a37*a31);
  a13=(a13*a37);
  a17=(a17+a13);
  a13=sin(a1);
  a36=(a36*a29);
  a35=(a35*a26);
  a36=(a36-a35);
  a20=(a20*a36);
  a13=(a13*a20);
  a17=(a17-a13);
  a13=cos(a1);
  a21=(a21*a36);
  a12=(a12*a21);
  a13=(a13*a12);
  a17=(a17+a13);
  a1=sin(a1);
  a32=(a32*a25);
  a25=(a9+a9);
  a25=(a25*a34);
  a32=(a32-a25);
  a9=(a9+a9);
  a9=(a9*a38);
  a32=(a32-a9);
  a22=(a22*a14);
  a32=(a32+a22);
  a8=(a8*a32);
  a1=(a1*a8);
  a17=(a17-a1);
  if (res[0]!=0) res[0][2]=a17;
  a17=(a5+a5);
  a1=(a30*a27);
  a17=(a17*a1);
  a33=(a33*a27);
  a17=(a17-a33);
  a33=arg[3]? arg[3][2] : 0;
  a17=(a17+a33);
  a4=(a4*a15);
  a17=(a17+a4);
  a5=(a5+a5);
  a30=(a30*a15);
  a5=(a5*a30);
  a17=(a17-a5);
  if (res[0]!=0) res[0][3]=a17;
  a27=(a27-a15);
  if (res[0]!=0) res[0][4]=a27;
  return 0;
}

CASADI_SYMBOL_EXPORT int adj_ERK_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f2(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int adj_ERK_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int adj_ERK_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void adj_ERK_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int adj_ERK_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void adj_ERK_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void adj_ERK_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void adj_ERK_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int adj_ERK_fun_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int adj_ERK_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real adj_ERK_fun_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* adj_ERK_fun_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* adj_ERK_fun_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* adj_ERK_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* adj_ERK_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int adj_ERK_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* adj_fun:(i0[4],i1,i2[0],i3[5],i4[5],i5[4],i6,i7,i8[0])->(o0[5],o1[5]) */
static int casadi_f3(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2, a3, a4, a5;
  a0=5.0000000000000000e-001;
  a1=arg[0]? arg[0][0] : 0;
  a2=arg[3]? arg[3][0] : 0;
  a3=(a1-a2);
  a3=(a0*a3);
  a4=arg[4]? arg[4][0] : 0;
  a3=(a3*a4);
  a1=(a1-a2);
  a4=(a4*a1);
  a4=(a0*a4);
  a3=(a3+a4);
  if (res[0]!=0) res[0][0]=a3;
  a3=arg[0]? arg[0][1] : 0;
  a4=arg[3]? arg[3][1] : 0;
  a1=(a3-a4);
  a1=(a0*a1);
  a2=arg[4]? arg[4][1] : 0;
  a1=(a1*a2);
  a3=(a3-a4);
  a2=(a2*a3);
  a2=(a0*a2);
  a1=(a1+a2);
  if (res[0]!=0) res[0][1]=a1;
  a1=arg[0]? arg[0][2] : 0;
  a2=arg[3]? arg[3][2] : 0;
  a3=(a1-a2);
  a3=(a0*a3);
  a4=arg[4]? arg[4][2] : 0;
  a3=(a3*a4);
  a1=(a1-a2);
  a4=(a4*a1);
  a4=(a0*a4);
  a3=(a3+a4);
  if (res[0]!=0) res[0][2]=a3;
  a3=arg[0]? arg[0][3] : 0;
  a4=arg[3]? arg[3][3] : 0;
  a1=(a3-a4);
  a1=(a0*a1);
  a2=arg[4]? arg[4][3] : 0;
  a1=(a1*a2);
  a3=(a3-a4);
  a2=(a2*a3);
  a2=(a0*a2);
  a1=(a1+a2);
  if (res[0]!=0) res[0][3]=a1;
  a1=arg[1]? arg[1][0] : 0;
  a2=arg[3]? arg[3][4] : 0;
  a3=(a1-a2);
  a4=arg[4]? arg[4][4] : 0;
  a5=(a0*a4);
  a3=(a3*a5);
  a1=(a1-a2);
  a0=(a0*a1);
  a0=(a0*a4);
  a3=(a3+a0);
  if (res[0]!=0) res[0][4]=a3;
  a3=arg[6]? arg[6][0] : 0;
  if (res[1]!=0) res[1][0]=a3;
  a3=0.;
  if (res[1]!=0) res[1][1]=a3;
  if (res[1]!=0) res[1][2]=a3;
  if (res[1]!=0) res[1][3]=a3;
  a3=arg[7]? arg[7][0] : 0;
  if (res[1]!=0) res[1][4]=a3;
  return 0;
}

CASADI_SYMBOL_EXPORT int adj_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f3(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int adj_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int adj_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void adj_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int adj_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void adj_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void adj_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void adj_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int adj_fun_n_in(void) { return 9;}

CASADI_SYMBOL_EXPORT casadi_int adj_fun_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real adj_fun_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* adj_fun_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    case 6: return "i6";
    case 7: return "i7";
    case 8: return "i8";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* adj_fun_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* adj_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s4;
    case 4: return casadi_s4;
    case 5: return casadi_s0;
    case 6: return casadi_s1;
    case 7: return casadi_s1;
    case 8: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* adj_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int adj_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 9;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* adjN_fun:(i0[4],i1[0],i2[4],i3[4],i4,i5[0])->(o0[4],o1[4]) */
static int casadi_f4(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2, a3, a4;
  a0=5.0000000000000000e-001;
  a1=arg[0]? arg[0][0] : 0;
  a2=arg[2]? arg[2][0] : 0;
  a3=(a1-a2);
  a3=(a0*a3);
  a4=arg[3]? arg[3][0] : 0;
  a3=(a3*a4);
  a1=(a1-a2);
  a4=(a4*a1);
  a4=(a0*a4);
  a3=(a3+a4);
  if (res[0]!=0) res[0][0]=a3;
  a3=arg[0]? arg[0][1] : 0;
  a4=arg[2]? arg[2][1] : 0;
  a1=(a3-a4);
  a1=(a0*a1);
  a2=arg[3]? arg[3][1] : 0;
  a1=(a1*a2);
  a3=(a3-a4);
  a2=(a2*a3);
  a2=(a0*a2);
  a1=(a1+a2);
  if (res[0]!=0) res[0][1]=a1;
  a1=arg[0]? arg[0][2] : 0;
  a2=arg[2]? arg[2][2] : 0;
  a3=(a1-a2);
  a3=(a0*a3);
  a4=arg[3]? arg[3][2] : 0;
  a3=(a3*a4);
  a1=(a1-a2);
  a4=(a4*a1);
  a4=(a0*a4);
  a3=(a3+a4);
  if (res[0]!=0) res[0][2]=a3;
  a3=arg[0]? arg[0][3] : 0;
  a4=arg[2]? arg[2][3] : 0;
  a1=(a3-a4);
  a1=(a0*a1);
  a2=arg[3]? arg[3][3] : 0;
  a1=(a1*a2);
  a3=(a3-a4);
  a2=(a2*a3);
  a0=(a0*a2);
  a1=(a1+a0);
  if (res[0]!=0) res[0][3]=a1;
  a1=arg[4]? arg[4][0] : 0;
  if (res[1]!=0) res[1][0]=a1;
  a1=0.;
  if (res[1]!=0) res[1][1]=a1;
  if (res[1]!=0) res[1][2]=a1;
  if (res[1]!=0) res[1][3]=a1;
  return 0;
}

CASADI_SYMBOL_EXPORT int adjN_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f4(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int adjN_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int adjN_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void adjN_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int adjN_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void adjN_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void adjN_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void adjN_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int adjN_fun_n_in(void) { return 6;}

CASADI_SYMBOL_EXPORT casadi_int adjN_fun_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real adjN_fun_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* adjN_fun_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* adjN_fun_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* adjN_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s2;
    case 2: return casadi_s0;
    case 3: return casadi_s0;
    case 4: return casadi_s1;
    case 5: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* adjN_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int adjN_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* impl_f_fun:(i0[4],i1,i2[0],i3[4],i4[0])->(o0[4]) */
static int casadi_f5(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a2, a3, a4, a5, a6, a7, a8, a9;
  a0=arg[3]? arg[3][0] : 0;
  a1=arg[0]? arg[0][1] : 0;
  a0=(a0-a1);
  if (res[0]!=0) res[0][0]=a0;
  a0=arg[3]? arg[3][1] : 0;
  a2=2.1205800000000000e-002;
  a3=arg[0]? arg[0][2] : 0;
  a4=cos(a3);
  a4=(a2*a4);
  a5=8.7317999999999996e-003;
  a6=sin(a3);
  a6=(a5*a6);
  a7=cos(a3);
  a6=(a6*a7);
  a7=casadi_sq(a1);
  a7=(a6*a7);
  a8=4.0789980000000003e-001;
  a9=sin(a3);
  a8=(a8*a9);
  a7=(a7+a8);
  a7=(a4*a7);
  a9=9.6046499999999993e-003;
  a10=arg[1]? arg[1][0] : 0;
  a11=sin(a3);
  a2=(a2*a11);
  a11=arg[0]? arg[0][3] : 0;
  a12=casadi_sq(a11);
  a12=(a2*a12);
  a12=(a10+a12);
  a13=1.7463599999999999e-002;
  a14=sin(a3);
  a13=(a13*a14);
  a14=cos(a3);
  a13=(a13*a14);
  a14=(a13*a1);
  a14=(a14*a11);
  a12=(a12-a14);
  a12=(a9*a12);
  a7=(a7-a12);
  a12=casadi_sq(a4);
  a14=1.0351980000000000e-001;
  a3=sin(a3);
  a3=casadi_sq(a3);
  a5=(a5*a3);
  a14=(a14+a5);
  a5=(a9*a14);
  a12=(a12-a5);
  a7=(a7/a12);
  a0=(a0-a7);
  if (res[0]!=0) res[0][1]=a0;
  a0=arg[3]? arg[3][2] : 0;
  a0=(a0-a11);
  if (res[0]!=0) res[0][2]=a0;
  a0=arg[3]? arg[3][3] : 0;
  a7=casadi_sq(a11);
  a2=(a2*a7);
  a10=(a10+a2);
  a13=(a13*a1);
  a13=(a13*a11);
  a10=(a10-a13);
  a10=(a4*a10);
  a1=casadi_sq(a1);
  a6=(a6*a1);
  a6=(a6+a8);
  a6=(a14*a6);
  a10=(a10-a6);
  a4=casadi_sq(a4);
  a9=(a9*a14);
  a4=(a4-a9);
  a10=(a10/a4);
  a0=(a0-a10);
  if (res[0]!=0) res[0][3]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int impl_f_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f5(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int impl_f_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int impl_f_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void impl_f_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int impl_f_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void impl_f_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void impl_f_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void impl_f_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int impl_f_fun_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int impl_f_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real impl_f_fun_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* impl_f_fun_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* impl_f_fun_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* impl_f_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s0;
    case 4: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* impl_f_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int impl_f_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* impl_jac_f_x_fun:(i0[4],i1,i2[0],i3[4],i4[0])->(o0[4x4]) */
static int casadi_f6(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a3, a4, a5, a6, a7, a8, a9;
  a0=0.;
  if (res[0]!=0) res[0][0]=a0;
  if (res[0]!=0) res[0][1]=a0;
  if (res[0]!=0) res[0][2]=a0;
  if (res[0]!=0) res[0][3]=a0;
  a1=-1.;
  if (res[0]!=0) res[0][4]=a1;
  a2=2.1205800000000000e-002;
  a3=arg[0]? arg[0][2] : 0;
  a4=cos(a3);
  a4=(a2*a4);
  a5=8.7317999999999996e-003;
  a6=sin(a3);
  a6=(a5*a6);
  a7=cos(a3);
  a8=(a6*a7);
  a9=arg[0]? arg[0][1] : 0;
  a10=(a9+a9);
  a10=(a8*a10);
  a10=(a4*a10);
  a11=9.6046499999999993e-003;
  a12=arg[0]? arg[0][3] : 0;
  a13=1.7463599999999999e-002;
  a14=sin(a3);
  a14=(a13*a14);
  a15=cos(a3);
  a16=(a14*a15);
  a17=(a12*a16);
  a17=(a11*a17);
  a10=(a10+a17);
  a17=casadi_sq(a4);
  a18=1.0351980000000000e-001;
  a19=sin(a3);
  a20=casadi_sq(a19);
  a20=(a5*a20);
  a18=(a18+a20);
  a20=(a11*a18);
  a17=(a17-a20);
  a10=(a10/a17);
  a10=(-a10);
  if (res[0]!=0) res[0][5]=a10;
  if (res[0]!=0) res[0][6]=a0;
  a10=(a12*a16);
  a10=(a4*a10);
  a20=(a9+a9);
  a20=(a8*a20);
  a20=(a18*a20);
  a10=(a10+a20);
  a20=casadi_sq(a4);
  a21=(a11*a18);
  a20=(a20-a21);
  a10=(a10/a20);
  if (res[0]!=0) res[0][7]=a10;
  if (res[0]!=0) res[0][8]=a0;
  a10=casadi_sq(a9);
  a21=cos(a3);
  a21=(a5*a21);
  a7=(a7*a21);
  a21=sin(a3);
  a6=(a6*a21);
  a7=(a7-a6);
  a6=(a10*a7);
  a21=4.0789980000000003e-001;
  a22=cos(a3);
  a22=(a21*a22);
  a6=(a6+a22);
  a6=(a4*a6);
  a10=(a8*a10);
  a23=sin(a3);
  a21=(a21*a23);
  a10=(a10+a21);
  a23=sin(a3);
  a23=(a2*a23);
  a24=(a10*a23);
  a6=(a6-a24);
  a24=casadi_sq(a12);
  a25=cos(a3);
  a25=(a2*a25);
  a26=(a24*a25);
  a27=cos(a3);
  a13=(a13*a27);
  a15=(a15*a13);
  a13=sin(a3);
  a14=(a14*a13);
  a15=(a15-a14);
  a14=(a9*a15);
  a14=(a12*a14);
  a26=(a26-a14);
  a26=(a11*a26);
  a6=(a6-a26);
  a6=(a6/a17);
  a10=(a4*a10);
  a26=arg[1]? arg[1][0] : 0;
  a14=sin(a3);
  a2=(a2*a14);
  a24=(a2*a24);
  a24=(a26+a24);
  a14=(a16*a9);
  a13=(a14*a12);
  a24=(a24-a13);
  a24=(a11*a24);
  a10=(a10-a24);
  a10=(a10/a17);
  a10=(a10/a17);
  a24=(a4+a4);
  a24=(a24*a23);
  a19=(a19+a19);
  a3=cos(a3);
  a19=(a19*a3);
  a5=(a5*a19);
  a19=(a11*a5);
  a24=(a24+a19);
  a10=(a10*a24);
  a6=(a6+a10);
  a6=(-a6);
  if (res[0]!=0) res[0][9]=a6;
  if (res[0]!=0) res[0][10]=a0;
  a6=casadi_sq(a12);
  a25=(a6*a25);
  a15=(a9*a15);
  a15=(a12*a15);
  a25=(a25-a15);
  a25=(a4*a25);
  a6=(a2*a6);
  a26=(a26+a6);
  a16=(a16*a9);
  a6=(a16*a12);
  a26=(a26-a6);
  a6=(a26*a23);
  a25=(a25-a6);
  a9=casadi_sq(a9);
  a8=(a8*a9);
  a8=(a8+a21);
  a21=(a8*a5);
  a9=(a9*a7);
  a9=(a9+a22);
  a9=(a18*a9);
  a21=(a21+a9);
  a25=(a25-a21);
  a25=(a25/a20);
  a26=(a4*a26);
  a18=(a18*a8);
  a26=(a26-a18);
  a26=(a26/a20);
  a26=(a26/a20);
  a18=(a4+a4);
  a18=(a18*a23);
  a5=(a11*a5);
  a18=(a18+a5);
  a26=(a26*a18);
  a25=(a25+a26);
  a25=(-a25);
  if (res[0]!=0) res[0][11]=a25;
  if (res[0]!=0) res[0][12]=a0;
  a0=(a12+a12);
  a0=(a2*a0);
  a0=(a0-a14);
  a11=(a11*a0);
  a11=(a11/a17);
  if (res[0]!=0) res[0][13]=a11;
  if (res[0]!=0) res[0][14]=a1;
  a12=(a12+a12);
  a2=(a2*a12);
  a2=(a2-a16);
  a4=(a4*a2);
  a4=(a4/a20);
  a4=(-a4);
  if (res[0]!=0) res[0][15]=a4;
  return 0;
}

CASADI_SYMBOL_EXPORT int impl_jac_f_x_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f6(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int impl_jac_f_x_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int impl_jac_f_x_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void impl_jac_f_x_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int impl_jac_f_x_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void impl_jac_f_x_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void impl_jac_f_x_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void impl_jac_f_x_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int impl_jac_f_x_fun_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int impl_jac_f_x_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real impl_jac_f_x_fun_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* impl_jac_f_x_fun_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* impl_jac_f_x_fun_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* impl_jac_f_x_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s0;
    case 4: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* impl_jac_f_x_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int impl_jac_f_x_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* impl_jac_f_u_fun:(i0[4],i1,i2[0],i3[4],i4[0])->(o0[4]) */
static int casadi_f7(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2, a3, a4, a5, a6, a7;
  a0=0.;
  if (res[0]!=0) res[0][0]=a0;
  a1=-9.6046499999999993e-003;
  a2=2.1205800000000000e-002;
  a3=arg[0]? arg[0][2] : 0;
  a4=cos(a3);
  a2=(a2*a4);
  a4=casadi_sq(a2);
  a5=9.6046499999999993e-003;
  a6=1.0351980000000000e-001;
  a7=8.7317999999999996e-003;
  a3=sin(a3);
  a3=casadi_sq(a3);
  a7=(a7*a3);
  a6=(a6+a7);
  a7=(a5*a6);
  a4=(a4-a7);
  a1=(a1/a4);
  a1=(-a1);
  if (res[0]!=0) res[0][1]=a1;
  if (res[0]!=0) res[0][2]=a0;
  a0=casadi_sq(a2);
  a5=(a5*a6);
  a0=(a0-a5);
  a2=(a2/a0);
  a2=(-a2);
  if (res[0]!=0) res[0][3]=a2;
  return 0;
}

CASADI_SYMBOL_EXPORT int impl_jac_f_u_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f7(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int impl_jac_f_u_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int impl_jac_f_u_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void impl_jac_f_u_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int impl_jac_f_u_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void impl_jac_f_u_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void impl_jac_f_u_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void impl_jac_f_u_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int impl_jac_f_u_fun_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int impl_jac_f_u_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real impl_jac_f_u_fun_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* impl_jac_f_u_fun_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* impl_jac_f_u_fun_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* impl_jac_f_u_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s0;
    case 4: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* impl_jac_f_u_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int impl_jac_f_u_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* impl_jac_f_xdot_fun:(i0[4],i1,i2[0],i3[4],i4[0])->(o0[4x4]) */
static int casadi_f8(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1;
  a0=1.;
  if (res[0]!=0) res[0][0]=a0;
  a1=0.;
  if (res[0]!=0) res[0][1]=a1;
  if (res[0]!=0) res[0][2]=a1;
  if (res[0]!=0) res[0][3]=a1;
  if (res[0]!=0) res[0][4]=a1;
  if (res[0]!=0) res[0][5]=a0;
  if (res[0]!=0) res[0][6]=a1;
  if (res[0]!=0) res[0][7]=a1;
  if (res[0]!=0) res[0][8]=a1;
  if (res[0]!=0) res[0][9]=a1;
  if (res[0]!=0) res[0][10]=a0;
  if (res[0]!=0) res[0][11]=a1;
  if (res[0]!=0) res[0][12]=a1;
  if (res[0]!=0) res[0][13]=a1;
  if (res[0]!=0) res[0][14]=a1;
  if (res[0]!=0) res[0][15]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int impl_jac_f_xdot_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f8(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int impl_jac_f_xdot_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int impl_jac_f_xdot_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void impl_jac_f_xdot_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int impl_jac_f_xdot_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void impl_jac_f_xdot_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void impl_jac_f_xdot_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void impl_jac_f_xdot_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int impl_jac_f_xdot_fun_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int impl_jac_f_xdot_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real impl_jac_f_xdot_fun_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* impl_jac_f_xdot_fun_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* impl_jac_f_xdot_fun_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* impl_jac_f_xdot_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s0;
    case 4: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* impl_jac_f_xdot_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int impl_jac_f_xdot_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* impl_jac_f_z_fun:(i0[4],i1,i2[0],i3[4],i4[0])->(o0) */
static int casadi_f9(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0;
  a0=0.;
  if (res[0]!=0) res[0][0]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int impl_jac_f_z_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f9(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int impl_jac_f_z_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int impl_jac_f_z_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void impl_jac_f_z_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int impl_jac_f_z_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void impl_jac_f_z_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void impl_jac_f_z_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void impl_jac_f_z_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int impl_jac_f_z_fun_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int impl_jac_f_z_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real impl_jac_f_z_fun_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* impl_jac_f_z_fun_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* impl_jac_f_z_fun_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* impl_jac_f_z_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s0;
    case 4: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* impl_jac_f_z_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int impl_jac_f_z_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* impl_jac_g_x_fun:(i0[4],i1,i2[0],i3[4],i4[0])->(o0) */
static int casadi_f10(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0;
  a0=0.;
  if (res[0]!=0) res[0][0]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int impl_jac_g_x_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f10(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int impl_jac_g_x_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int impl_jac_g_x_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void impl_jac_g_x_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int impl_jac_g_x_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void impl_jac_g_x_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void impl_jac_g_x_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void impl_jac_g_x_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int impl_jac_g_x_fun_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int impl_jac_g_x_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real impl_jac_g_x_fun_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* impl_jac_g_x_fun_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* impl_jac_g_x_fun_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* impl_jac_g_x_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s0;
    case 4: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* impl_jac_g_x_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int impl_jac_g_x_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* impl_jac_g_u_fun:(i0[4],i1,i2[0],i3[4],i4[0])->(o0) */
static int casadi_f11(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0;
  a0=0.;
  if (res[0]!=0) res[0][0]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int impl_jac_g_u_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f11(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int impl_jac_g_u_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int impl_jac_g_u_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void impl_jac_g_u_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int impl_jac_g_u_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void impl_jac_g_u_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void impl_jac_g_u_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void impl_jac_g_u_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int impl_jac_g_u_fun_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int impl_jac_g_u_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real impl_jac_g_u_fun_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* impl_jac_g_u_fun_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* impl_jac_g_u_fun_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* impl_jac_g_u_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s0;
    case 4: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* impl_jac_g_u_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int impl_jac_g_u_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* impl_jac_g_z_fun:(i0[4],i1,i2[0],i3[4],i4[0])->(o0) */
static int casadi_f12(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0;
  a0=0.;
  if (res[0]!=0) res[0][0]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int impl_jac_g_z_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f12(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int impl_jac_g_z_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int impl_jac_g_z_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void impl_jac_g_z_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int impl_jac_g_z_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void impl_jac_g_z_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void impl_jac_g_z_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void impl_jac_g_z_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int impl_jac_g_z_fun_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int impl_jac_g_z_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real impl_jac_g_z_fun_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* impl_jac_g_z_fun_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* impl_jac_g_z_fun_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* impl_jac_g_z_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s0;
    case 4: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* impl_jac_g_z_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int impl_jac_g_z_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* h_fun:(states[4],controls,params[0])->(h[5]) */
static int casadi_f13(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0;
  a0=arg[0]? arg[0][0] : 0;
  if (res[0]!=0) res[0][0]=a0;
  a0=arg[0]? arg[0][1] : 0;
  if (res[0]!=0) res[0][1]=a0;
  a0=arg[0]? arg[0][2] : 0;
  if (res[0]!=0) res[0][2]=a0;
  a0=arg[0]? arg[0][3] : 0;
  if (res[0]!=0) res[0][3]=a0;
  a0=arg[1]? arg[1][0] : 0;
  if (res[0]!=0) res[0][4]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int h_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f13(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int h_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int h_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void h_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int h_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void h_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void h_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void h_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int h_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int h_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real h_fun_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* h_fun_name_in(casadi_int i){
  switch (i) {
    case 0: return "states";
    case 1: return "controls";
    case 2: return "params";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* h_fun_name_out(casadi_int i){
  switch (i) {
    case 0: return "h";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* h_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* h_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int h_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* path_con_fun:(states[4],controls,params[0])->(general_con[]) */
static int casadi_f14(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT int path_con_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f14(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int path_con_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int path_con_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void path_con_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int path_con_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void path_con_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void path_con_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void path_con_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int path_con_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int path_con_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real path_con_fun_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* path_con_fun_name_in(casadi_int i){
  switch (i) {
    case 0: return "states";
    case 1: return "controls";
    case 2: return "params";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* path_con_fun_name_out(casadi_int i){
  switch (i) {
    case 0: return "general_con";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* path_con_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* path_con_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int path_con_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* path_con_N_fun:(states[4],params[0])->(general_con_N[]) */
static int casadi_f15(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT int path_con_N_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f15(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int path_con_N_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int path_con_N_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void path_con_N_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int path_con_N_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void path_con_N_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void path_con_N_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void path_con_N_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int path_con_N_fun_n_in(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_int path_con_N_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real path_con_N_fun_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* path_con_N_fun_name_in(casadi_int i){
  switch (i) {
    case 0: return "states";
    case 1: return "params";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* path_con_N_fun_name_out(casadi_int i){
  switch (i) {
    case 0: return "general_con_N";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* path_con_N_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* path_con_N_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int path_con_N_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* obji_fun:(i0[4],i1,i2[0],i3[5],i4[5])->(o0) */
static int casadi_f16(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2, a3, a4, a5;
  a0=5.0000000000000000e-001;
  a1=arg[0]? arg[0][0] : 0;
  a2=arg[3]? arg[3][0] : 0;
  a3=(a1-a2);
  a3=(a0*a3);
  a4=arg[4]? arg[4][0] : 0;
  a3=(a3*a4);
  a1=(a1-a2);
  a3=(a3*a1);
  a1=arg[0]? arg[0][1] : 0;
  a2=arg[3]? arg[3][1] : 0;
  a4=(a1-a2);
  a4=(a0*a4);
  a5=arg[4]? arg[4][1] : 0;
  a4=(a4*a5);
  a1=(a1-a2);
  a4=(a4*a1);
  a3=(a3+a4);
  a4=arg[0]? arg[0][2] : 0;
  a1=arg[3]? arg[3][2] : 0;
  a2=(a4-a1);
  a2=(a0*a2);
  a5=arg[4]? arg[4][2] : 0;
  a2=(a2*a5);
  a4=(a4-a1);
  a2=(a2*a4);
  a3=(a3+a2);
  a2=arg[0]? arg[0][3] : 0;
  a4=arg[3]? arg[3][3] : 0;
  a1=(a2-a4);
  a1=(a0*a1);
  a5=arg[4]? arg[4][3] : 0;
  a1=(a1*a5);
  a2=(a2-a4);
  a1=(a1*a2);
  a3=(a3+a1);
  a1=arg[1]? arg[1][0] : 0;
  a2=arg[3]? arg[3][4] : 0;
  a4=(a1-a2);
  a0=(a0*a4);
  a4=arg[4]? arg[4][4] : 0;
  a0=(a0*a4);
  a1=(a1-a2);
  a0=(a0*a1);
  a3=(a3+a0);
  if (res[0]!=0) res[0][0]=a3;
  return 0;
}

CASADI_SYMBOL_EXPORT int obji_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f16(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int obji_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int obji_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void obji_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int obji_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void obji_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void obji_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void obji_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int obji_fun_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int obji_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real obji_fun_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* obji_fun_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* obji_fun_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* obji_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s4;
    case 4: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* obji_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int obji_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* objN_fun:(i0[4],i1[0],i2[4],i3[4])->(o0) */
static int casadi_f17(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2, a3, a4, a5;
  a0=5.0000000000000000e-001;
  a1=arg[0]? arg[0][0] : 0;
  a2=arg[2]? arg[2][0] : 0;
  a3=(a1-a2);
  a3=(a0*a3);
  a4=arg[3]? arg[3][0] : 0;
  a3=(a3*a4);
  a1=(a1-a2);
  a3=(a3*a1);
  a1=arg[0]? arg[0][1] : 0;
  a2=arg[2]? arg[2][1] : 0;
  a4=(a1-a2);
  a4=(a0*a4);
  a5=arg[3]? arg[3][1] : 0;
  a4=(a4*a5);
  a1=(a1-a2);
  a4=(a4*a1);
  a3=(a3+a4);
  a4=arg[0]? arg[0][2] : 0;
  a1=arg[2]? arg[2][2] : 0;
  a2=(a4-a1);
  a2=(a0*a2);
  a5=arg[3]? arg[3][2] : 0;
  a2=(a2*a5);
  a4=(a4-a1);
  a2=(a2*a4);
  a3=(a3+a2);
  a2=arg[0]? arg[0][3] : 0;
  a4=arg[2]? arg[2][3] : 0;
  a1=(a2-a4);
  a0=(a0*a1);
  a1=arg[3]? arg[3][3] : 0;
  a0=(a0*a1);
  a2=(a2-a4);
  a0=(a0*a2);
  a3=(a3+a0);
  if (res[0]!=0) res[0][0]=a3;
  return 0;
}

CASADI_SYMBOL_EXPORT int objN_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f17(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int objN_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int objN_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void objN_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int objN_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void objN_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void objN_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void objN_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int objN_fun_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int objN_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real objN_fun_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* objN_fun_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* objN_fun_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* objN_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s2;
    case 2: return casadi_s0;
    case 3: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* objN_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int objN_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* gi_fun:(i0[4],i1,i2[0],i3[5],i4[5])->(o0[4],o1) */
static int casadi_f18(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2, a3, a4, a5;
  a0=5.0000000000000000e-001;
  a1=arg[0]? arg[0][0] : 0;
  a2=arg[3]? arg[3][0] : 0;
  a3=(a1-a2);
  a3=(a0*a3);
  a4=arg[4]? arg[4][0] : 0;
  a3=(a3*a4);
  a1=(a1-a2);
  a4=(a4*a1);
  a4=(a0*a4);
  a3=(a3+a4);
  if (res[0]!=0) res[0][0]=a3;
  a3=arg[0]? arg[0][1] : 0;
  a4=arg[3]? arg[3][1] : 0;
  a1=(a3-a4);
  a1=(a0*a1);
  a2=arg[4]? arg[4][1] : 0;
  a1=(a1*a2);
  a3=(a3-a4);
  a2=(a2*a3);
  a2=(a0*a2);
  a1=(a1+a2);
  if (res[0]!=0) res[0][1]=a1;
  a1=arg[0]? arg[0][2] : 0;
  a2=arg[3]? arg[3][2] : 0;
  a3=(a1-a2);
  a3=(a0*a3);
  a4=arg[4]? arg[4][2] : 0;
  a3=(a3*a4);
  a1=(a1-a2);
  a4=(a4*a1);
  a4=(a0*a4);
  a3=(a3+a4);
  if (res[0]!=0) res[0][2]=a3;
  a3=arg[0]? arg[0][3] : 0;
  a4=arg[3]? arg[3][3] : 0;
  a1=(a3-a4);
  a1=(a0*a1);
  a2=arg[4]? arg[4][3] : 0;
  a1=(a1*a2);
  a3=(a3-a4);
  a2=(a2*a3);
  a2=(a0*a2);
  a1=(a1+a2);
  if (res[0]!=0) res[0][3]=a1;
  a1=arg[1]? arg[1][0] : 0;
  a2=arg[3]? arg[3][4] : 0;
  a3=(a1-a2);
  a4=arg[4]? arg[4][4] : 0;
  a5=(a0*a4);
  a3=(a3*a5);
  a1=(a1-a2);
  a0=(a0*a1);
  a0=(a0*a4);
  a3=(a3+a0);
  if (res[1]!=0) res[1][0]=a3;
  return 0;
}

CASADI_SYMBOL_EXPORT int gi_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f18(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int gi_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int gi_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void gi_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int gi_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void gi_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void gi_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void gi_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int gi_fun_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int gi_fun_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real gi_fun_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* gi_fun_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* gi_fun_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* gi_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s4;
    case 4: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* gi_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int gi_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* gN_fun:(i0[4],i1[0],i2[4],i3[4])->(o0[4]) */
static int casadi_f19(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2, a3, a4;
  a0=5.0000000000000000e-001;
  a1=arg[0]? arg[0][0] : 0;
  a2=arg[2]? arg[2][0] : 0;
  a3=(a1-a2);
  a3=(a0*a3);
  a4=arg[3]? arg[3][0] : 0;
  a3=(a3*a4);
  a1=(a1-a2);
  a4=(a4*a1);
  a4=(a0*a4);
  a3=(a3+a4);
  if (res[0]!=0) res[0][0]=a3;
  a3=arg[0]? arg[0][1] : 0;
  a4=arg[2]? arg[2][1] : 0;
  a1=(a3-a4);
  a1=(a0*a1);
  a2=arg[3]? arg[3][1] : 0;
  a1=(a1*a2);
  a3=(a3-a4);
  a2=(a2*a3);
  a2=(a0*a2);
  a1=(a1+a2);
  if (res[0]!=0) res[0][1]=a1;
  a1=arg[0]? arg[0][2] : 0;
  a2=arg[2]? arg[2][2] : 0;
  a3=(a1-a2);
  a3=(a0*a3);
  a4=arg[3]? arg[3][2] : 0;
  a3=(a3*a4);
  a1=(a1-a2);
  a4=(a4*a1);
  a4=(a0*a4);
  a3=(a3+a4);
  if (res[0]!=0) res[0][2]=a3;
  a3=arg[0]? arg[0][3] : 0;
  a4=arg[2]? arg[2][3] : 0;
  a1=(a3-a4);
  a1=(a0*a1);
  a2=arg[3]? arg[3][3] : 0;
  a1=(a1*a2);
  a3=(a3-a4);
  a2=(a2*a3);
  a0=(a0*a2);
  a1=(a1+a0);
  if (res[0]!=0) res[0][3]=a1;
  return 0;
}

CASADI_SYMBOL_EXPORT int gN_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f19(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int gN_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int gN_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void gN_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int gN_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void gN_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void gN_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void gN_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int gN_fun_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int gN_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real gN_fun_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* gN_fun_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* gN_fun_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* gN_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s2;
    case 2: return casadi_s0;
    case 3: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* gN_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int gN_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* Hi_fun:(i0[4],i1,i2[0],i3[5],i4[5])->(o0[5x5]) */
static int casadi_f20(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1;
  a0=1.;
  if (res[0]!=0) res[0][0]=a0;
  a1=0.;
  if (res[0]!=0) res[0][1]=a1;
  if (res[0]!=0) res[0][2]=a1;
  if (res[0]!=0) res[0][3]=a1;
  if (res[0]!=0) res[0][4]=a1;
  if (res[0]!=0) res[0][5]=a1;
  if (res[0]!=0) res[0][6]=a0;
  if (res[0]!=0) res[0][7]=a1;
  if (res[0]!=0) res[0][8]=a1;
  if (res[0]!=0) res[0][9]=a1;
  if (res[0]!=0) res[0][10]=a1;
  if (res[0]!=0) res[0][11]=a1;
  if (res[0]!=0) res[0][12]=a0;
  if (res[0]!=0) res[0][13]=a1;
  if (res[0]!=0) res[0][14]=a1;
  if (res[0]!=0) res[0][15]=a1;
  if (res[0]!=0) res[0][16]=a1;
  if (res[0]!=0) res[0][17]=a1;
  if (res[0]!=0) res[0][18]=a0;
  if (res[0]!=0) res[0][19]=a1;
  if (res[0]!=0) res[0][20]=a1;
  if (res[0]!=0) res[0][21]=a1;
  if (res[0]!=0) res[0][22]=a1;
  if (res[0]!=0) res[0][23]=a1;
  if (res[0]!=0) res[0][24]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int Hi_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f20(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int Hi_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int Hi_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Hi_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int Hi_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Hi_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void Hi_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void Hi_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int Hi_fun_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int Hi_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real Hi_fun_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Hi_fun_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Hi_fun_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Hi_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s4;
    case 4: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Hi_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int Hi_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* HN_fun:(i0[4],i1[0],i2[4],i3[4])->(o0[4x4]) */
static int casadi_f21(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1;
  a0=1.;
  if (res[0]!=0) res[0][0]=a0;
  a1=0.;
  if (res[0]!=0) res[0][1]=a1;
  if (res[0]!=0) res[0][2]=a1;
  if (res[0]!=0) res[0][3]=a1;
  if (res[0]!=0) res[0][4]=a1;
  if (res[0]!=0) res[0][5]=a0;
  if (res[0]!=0) res[0][6]=a1;
  if (res[0]!=0) res[0][7]=a1;
  if (res[0]!=0) res[0][8]=a1;
  if (res[0]!=0) res[0][9]=a1;
  if (res[0]!=0) res[0][10]=a0;
  if (res[0]!=0) res[0][11]=a1;
  if (res[0]!=0) res[0][12]=a1;
  if (res[0]!=0) res[0][13]=a1;
  if (res[0]!=0) res[0][14]=a1;
  if (res[0]!=0) res[0][15]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int HN_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f21(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int HN_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int HN_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void HN_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int HN_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void HN_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void HN_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void HN_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int HN_fun_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int HN_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real HN_fun_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* HN_fun_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* HN_fun_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* HN_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s2;
    case 2: return casadi_s0;
    case 3: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* HN_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int HN_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* Ji_fun:(i0[4],i1,i2[0],i3[5],i4[5])->(o0[5x4],o1[5]) */
static int casadi_f22(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1;
  a0=arg[4]? arg[4][0] : 0;
  a0=sqrt(a0);
  if (res[0]!=0) res[0][0]=a0;
  a0=0.;
  if (res[0]!=0) res[0][1]=a0;
  if (res[0]!=0) res[0][2]=a0;
  if (res[0]!=0) res[0][3]=a0;
  if (res[0]!=0) res[0][4]=a0;
  if (res[0]!=0) res[0][5]=a0;
  a1=arg[4]? arg[4][1] : 0;
  a1=sqrt(a1);
  if (res[0]!=0) res[0][6]=a1;
  if (res[0]!=0) res[0][7]=a0;
  if (res[0]!=0) res[0][8]=a0;
  if (res[0]!=0) res[0][9]=a0;
  if (res[0]!=0) res[0][10]=a0;
  if (res[0]!=0) res[0][11]=a0;
  a1=arg[4]? arg[4][2] : 0;
  a1=sqrt(a1);
  if (res[0]!=0) res[0][12]=a1;
  if (res[0]!=0) res[0][13]=a0;
  if (res[0]!=0) res[0][14]=a0;
  if (res[0]!=0) res[0][15]=a0;
  if (res[0]!=0) res[0][16]=a0;
  if (res[0]!=0) res[0][17]=a0;
  a1=arg[4]? arg[4][3] : 0;
  a1=sqrt(a1);
  if (res[0]!=0) res[0][18]=a1;
  if (res[0]!=0) res[0][19]=a0;
  if (res[1]!=0) res[1][0]=a0;
  if (res[1]!=0) res[1][1]=a0;
  if (res[1]!=0) res[1][2]=a0;
  if (res[1]!=0) res[1][3]=a0;
  a0=arg[4]? arg[4][4] : 0;
  a0=sqrt(a0);
  if (res[1]!=0) res[1][4]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int Ji_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f22(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int Ji_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int Ji_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Ji_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int Ji_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Ji_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void Ji_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void Ji_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int Ji_fun_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int Ji_fun_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real Ji_fun_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Ji_fun_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Ji_fun_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Ji_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s4;
    case 4: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Ji_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s7;
    case 1: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int Ji_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* JN_fun:(i0[4],i1[0],i2[4],i3[4])->(o0[4x4]) */
static int casadi_f23(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1;
  a0=arg[3]? arg[3][0] : 0;
  a0=sqrt(a0);
  if (res[0]!=0) res[0][0]=a0;
  a0=0.;
  if (res[0]!=0) res[0][1]=a0;
  if (res[0]!=0) res[0][2]=a0;
  if (res[0]!=0) res[0][3]=a0;
  if (res[0]!=0) res[0][4]=a0;
  a1=arg[3]? arg[3][1] : 0;
  a1=sqrt(a1);
  if (res[0]!=0) res[0][5]=a1;
  if (res[0]!=0) res[0][6]=a0;
  if (res[0]!=0) res[0][7]=a0;
  if (res[0]!=0) res[0][8]=a0;
  if (res[0]!=0) res[0][9]=a0;
  a1=arg[3]? arg[3][2] : 0;
  a1=sqrt(a1);
  if (res[0]!=0) res[0][10]=a1;
  if (res[0]!=0) res[0][11]=a0;
  if (res[0]!=0) res[0][12]=a0;
  if (res[0]!=0) res[0][13]=a0;
  if (res[0]!=0) res[0][14]=a0;
  a0=arg[3]? arg[3][3] : 0;
  a0=sqrt(a0);
  if (res[0]!=0) res[0][15]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int JN_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f23(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int JN_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int JN_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void JN_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int JN_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void JN_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void JN_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void JN_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int JN_fun_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int JN_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real JN_fun_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* JN_fun_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* JN_fun_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* JN_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s2;
    case 2: return casadi_s0;
    case 3: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* JN_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int JN_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* Ci_fun:(i0[4],i1,i2[0])->(o0[0x4],o1[0]) */
static int casadi_f24(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT int Ci_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f24(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int Ci_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int Ci_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Ci_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int Ci_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Ci_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void Ci_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void Ci_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int Ci_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int Ci_fun_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real Ci_fun_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Ci_fun_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Ci_fun_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Ci_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Ci_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s8;
    case 1: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int Ci_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* CN_fun:(i0[4],i1[0])->(o0[0x4]) */
static int casadi_f25(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT int CN_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f25(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int CN_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int CN_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void CN_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int CN_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void CN_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void CN_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void CN_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int CN_fun_n_in(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_int CN_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real CN_fun_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* CN_fun_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* CN_fun_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* CN_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* CN_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s8;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int CN_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
