function x_dot = dynsys(t,theta0,d_theta0,theta1,d_theta1,tau)
%DYNSYS
%    X_DOT = DYNSYS(T,THETA0,D_THETA0,THETA1,D_THETA1,TAU)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    27-Apr-2020 19:20:20

t2 = cos(theta1);
t3 = sin(theta1);
t4 = t2.^2;
t5 = t3.^2;
t6 = t5.*8.386588286999999e-5;
t11 = t4.*4.4968595364e-4;
t7 = t6-t11+9.942714470699999e-4;
t8 = 1.0./t7;
t9 = tau.*9.604649999999999e-3;
t10 = t3.*4.078998e-1;
t12 = d_theta1^2;
t13 = t3.*t12.*2.0367428697e-4;
t14 = d_theta0^2;
t15 = t2.*t3.*t14.*8.7318e-3;
t16 = t10+t15;
t29 = t2.*t16.*2.12058e-2;
t30 = d_theta0.*d_theta1.*t2.*t3.*1.6773176574e-4;
t17 = t9+t13-t29-t30;
t20 = t3.*t12.*2.12058e-2;
t21 = d_theta0.*d_theta1.*t2.*t3.*1.74636e-2;
t22 = t20-t21+tau;
t23 = t2.*t22.*2.12058e-2;
t24 = t2.*t3.*8.7318e-3;
t25 = t10+t24;
t26 = t5.*8.7318e-3;
t27 = t26+1.035198e-1;
t28 = t25.*t27;
t18 = t23-t28;
t19 = 1.0./t7.^2;
t31 = t18.^2;
x_dot = [t8.*t17;t8.*(t9-t2.*(t10+t2.*t3.*t17.^2.*t19.*8.7318e-3).*2.12058e-2+t3.*t19.*t31.*2.0367428697e-4+t2.*t3.*t17.*t18.*t19.*1.6773176574e-4);-t8.*t18;t8.*(t28-t2.*(tau+t3.*t19.*t31.*2.12058e-2+t2.*t3.*t17.*t18.*t19.*1.74636e-2).*2.12058e-2)];
